blog/urls.py
from django.urls import path
from django.contrib import admin

from blog.views import Home, ListLadies, ListMaterials, ListArticles, ShowArticle

app_name = 'blog'

urlpatterns = [
    path('', Home.as_view(), name='about'),
    path('ladies/', ListLadies.as_view(), name='ladies'),
    path('materials/', ListMaterials.as_view(), name='material'),
    path('blog/', ListArticles.as_view(), name='blog'),
    path('blog/article/<slug:slug>/', ShowArticle.as_view(), name='article'),
]

website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include('blog.urls', namespace='blog')),
]

blog/models.py
from django.db import models
from django.utils import timezone
from ckeditor.fields import RichTextField

class Tag(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

class Article(models.Model):
    title = models.CharField(max_length=200)
    slug = models.CharField(max_length=200)
    date = models.DateTimeField(default=timezone.now)
    tags = models.ManyToManyField(Tag)
    category = models.CharField(max_length=200)
    author = models.CharField(max_length=200)
    comments = models.BooleanField(default=True)
    content = RichTextField()

    def __str__(self):
        return self.title

    class Meta:
        ordering = ('-date',)

blog/views.py
from django.contrib.staticfiles.templatetags.staticfiles import static
from django.views.generic.base import TemplateView
from django.views.generic.list import ListView
from django.template import RequestContext
from django.shortcuts import render, get_object_or_404, redirect

from .models import Article

from pathlib import Path
import yaml
import re


class Home(TemplateView):
    template_name = "blog/index.html"


class ListLadies(ListView):
    template_name = 'blog/ladies.html'
    context_object_name = 'ladies'

    def get_context_data(self, **kwargs):
        context = super(ListLadies, self).get_context_data()

        context['medias'] = ['facebook', 'twitter', 'github']

        return context

    def get_queryset(self):
        with open(f'{Path(__file__).parents[0]}/content/ladies.yml', 'rb') as stream:
            try:
                ladies = yaml.load(stream)
            except yaml.YAMLError as exc:
                ladies = []
        return ladies


class ListMaterials(ListView):
    template_name = 'blog/materials.html'
    context_object_name = 'materials'

    def get_queryset(self):
        with open(f'{Path(__file__).parents[0]}/content/materials.yml', 'rb') as stream:
            try:
                materials = yaml.load(stream)
            except yaml.YAMLError as exc:
                materials = []
        return materials


class ListArticles(ListView):
    template_name = "blog/articles.html"
    context_object_name = "articles"
    model = Article

    def get_queryset(self):
        articles = super().get_queryset()
        return articles

class ShowArticle(TemplateView):
    template_name = "blog/article.html"
    model = Article

    def get_context_data(self, **kwargs):
        context = super(ShowArticle, self).get_context_data()
        slug = self.kwargs['slug']
        article = get_object_or_404(Article, slug=slug)
        context['article'] = article
        return context

blog/templates/blog/article.html
{% extends "blog/layouts/base.html" %}

{% block title %}{{ article.title }}{% endblock %}

{% load static %}
{% load datetime %}

{% block extra_meta %}
	{% if article.description %}
		<meta name="description" content="{{ article.description }}">
		<meta name="twitter:description" content="{{ article.description }}">
		<meta property="og:description" content="{{ article.description }}">
	{% endif %}

	{% if article.imagefeatured %}
		<meta name="twitter:image" content="{{ SITEURL }}/theme/images/{{ article.imagefeatured }}">
		<meta property="og:image" content="{{ SITEURL }}/theme/images/{{ article.imagefeatured  }}">
	{% endif %}

	<meta name="twitter:title" content="{{ article.title }}">
	<meta name="twitter:creator" content="@PyLadiesDF">
	<meta property="og:locale" content="pt_BR">
	<meta property="og:type" content="article">
	<meta property="og:title" content="{{ article.title }}">
	<!-- <meta property="og:url" content="{{ SITEURL }}/{{ article.url }}"> -->
{% endblock %}

{% block body_class %}post-template{% endblock %}

{% block extra_header %}
<div class="notepad-post-title-simple row">
    <div class="small-12 columns">
        <div class="notepad-post-meta-simple">
            <h1>{{ article.title }}</h1>
            <p>by {{ article.author }};
					</p>
        </div>
    </div>
</div>
{% endblock %}

{% block content %}
	<article class="notepad-post-content post tag-simple">
	    <div>
	        {{ article.content|safe }}
	    </div>
	    <div class="cf"></div>
      {% include 'blog/share.html' %}
      <div class="cf"></div>
	</article>
{% endblock %}

blog/templates/blog/articles.html
{% extends "blog/layouts/base.html" %}

{% block title %}Pyladies DF - Blog{% endblock %}

{% load static %}
{% load datetime %}

{% block content %}
<article class="notepad-page-content">
    <div class="title small-12 columns">
        <h1>BLOG</h1>
    </div>
    <div class="entry-content">
        <div>
            <input type="text" maxlength="60" id="tipue_search_input" />
        </div>
        <div id="tipue_search_content"></div>
    </div>
    <div>
        <ul class="post-list">

        {% for article in articles %}
            <li>
                <article><i class="fa fa-star-half-o"></i>
                    <a href="{% url 'blog:article' slug=article.slug %}">{{ article.title }}
                        <span class="entry-author"> por {{ article.author }} </span>
                        <span class="entry-date">{{ article.date|date:"F d, Y" }}</span>>
                    </a>
                </article>
            </li>
        {% endfor %}
        </ul>
    </div>
</article>
<div class="cf"></div>
{% endblock %}

blog/templates/blog/base.html
<!DOCTYPE html>
<html>
    <head>
    {% include 'blog/head.html' %}
    {% block extra_meta %}
      <meta name="description"
            content="Ninguém pode fazer você se sentir inferior sem o seu consentimento (Eleanor Roosevelt)">
    {% endblock %}
	{% include 'blog/scripts.html' %}
    </head>
    <body class="{% block body_class %}{% endblock %}">
        <header class="notepad-site-head">
            {% include 'blog/header.html' %}
            {% block extra_header %}{% endblock %}
        </header>
        <main class="notepad-content row" role="main">
        {% block content %}{% endblock %}
        </main>
        {% include 'blog/footer.html' %}
        {% include 'blog/scripts_footer.html' %}
    </body>
</html>

blog/templates/blog/includes/footer.html
<footer class="notepad-site-footer" >
    <div class="copyright">
        <section>All content copyright <a href="{% url 'blog:about' %}">PyLadies DF</a> &copy; 2018 &bull; All rights reserved.</section>
    </div>
    <div class="social-icons">

        <a href="http://twitter.com/PyLadiesDF" data-toggle="tooltip" title="Twitter">
            <span class="fa-stack fa-lg">
                <i class="fa fa-circle fa-stack-2x fa-inverse"></i>
                <i class="fa fa-twitter fa-stack-1x"></i>
            </span>
        </a>
        <a href="http://github.com/pyladiesdf" data-toggle="tooltip" title="Github">
            <span class="fa-stack fa-lg">
                <i class="fa fa-circle fa-stack-2x fa-inverse"></i>
                <i class="fa fa-github fa-stack-1x"></i>
            </span>
        </a>
        <a href="http://facebook.com/pyladiesdf" data-toggle="tooltip" title="Facebook">
            <span class="fa-stack fa-lg">
                <i class="fa fa-circle fa-stack-2x fa-inverse"></i>
                <i class="fa fa-facebook fa-stack-1x"></i>
            </span>
        </a>
        <a href="https://www.instagram.com/pyladiesdf/" data-toggle="tooltip" title="Instagram">
            <span class="fa-stack fa-lg">
                <i class="fa fa-circle fa-stack-2x fa-inverse"></i>
                <i class="fa fa-instagram fa-stack-1x"></i>
            </span>
        </a>
    </div>
    <div class="cf"></div>
</footer>

blog/templates/blog/includes/head.html
<meta charset="utf-8">
<title>PyLadies DF</title>

<meta property="og:site_name" content="PyLadies DF">
<meta name="twitter:card" content="summary">

<!-- http://t.co/dKP3o1e -->
<meta name="HandheldFriendly" content="True">
<meta name="MobileOptimized" content="320">
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />


<link href='https://fonts.googleapis.com/css?family=Montserrat:400,700|Open+Sans:400,600,300,800,700' rel='stylesheet' type='text/css'>
<link href='https://fonts.googleapis.com/css?family=Shadows+Into+Light' rel='stylesheet' type='text/css'>
<link href='https://fonts.googleapis.com/css?family=Indie+Flower' rel='stylesheet' type='text/css'>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet" type='text/css'>

{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'blog/css/normalize.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'blog/css/nprogress.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'blog/css/foundation.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'blog/css/style.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'blog/css/post.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'blog/tipuesearch/tipuesearch.css' %}">

{% if page %}
<!--Load Mathjax-->
<script type="text/javascript" src="http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>
        <script>
        MathJax.Hub.Config({
            config: ["MMLorHTML.js"],
            extensions: ["tex2jax.js","TeX/AMSmath.js","TeX/AMSsymbols.js"],
            jax: ["input/TeX"],
            tex2jax: {
                inlineMath: [ ['$','$'], ["\\(","\\)"] ],
                displayMath: [ ['$$','$$'], ["\\[","\\]"] ],
                processEscapes: false
            },
            TeX: {
                TagSide: "right",
                TagIndent: ".8em",
                MultLineWidth: "85%",
                equationNumbers: {
                   autoNumber: "AMS",
                },
                unicode: {
                   fonts: "STIXGeneral,'Arial Unicode MS'"
                }
            },
            showProcessingMessages: false
        });
    </script>
{% endif %}

<!-- Icons -->
<!-- 16x16 -->
<link rel="shortcut icon" href="{% static 'blog/img/favicon.ico' %}">
<!-- 32x32 -->
<link rel="shortcut icon" href="{% static 'blog/img/favicon.png' %}">

blog/templates/blog/includes/header.html
{% load static %}

<div class="notepad-site-head-menu">
    <a class="notepad-blog-logo small-6 medium-3 columns" href="/">
        <img width="146" height="60" src="{% static 'blog/img/pyladiesdf.png' %}" alt="Pyladies Logo" />
    </a>
    <div class="notepad-blog-menu small-12 medium-9 columns">
        <div class="notepad-mobile-menu show-for-small">
            <a href="#"><i class="fa fa-bars"></i></a>
        </div>
        <ul class="notepad-menu">
            <li class="notepad-mobile-close-btn show-for-small text-right">
                <a href="#"><i class="fa fa-times"></i></a>
            </li>
            <li><a href="{% url 'blog:about' %}">Sobre</a></li>
            <li><a href="{% url 'blog:ladies' %}">Ladies</a></li>
            <li><a href="{% url 'blog:material' %}">Materiais</a></li>
            <li><a href="{% url 'blog:blog' %}">Blog</a></li>
        </ul>
    </div>
    <div class="clearfix"></div>
</div>

blog/templates/blog/includes/scripts.html
{% load static %}
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<script>window.jQuery || document.write('<script src="{% static 'blog/js/jquery-1.11.1.min.js' %}"><\/script>')</script>
<script src="{% static 'blog/js/modernizr.js' %}"></script>
<script src="{% static 'blog/js/foundation.min.js' %}"></script>

{% if page %}
<script src="{% static 'blog/js/background-check.js' %}"></script>
<script src="{% static 'blog/js/post-header-animations.js' %}"></script>
{% endif %}

<script src="{% static 'blog/js/notepad.js' %}"></script>
<script src="{% static 'blog/js/scripts.min.js' %}"></script>
<script src="{% static 'blog/js/nprogress.js' %}"></script>
<script src="{% static 'blog/tipuesearch/tipuesearch_set.js' %}"></script>
<script src="{% static 'blog/tipuesearch/tipuesearch.min.js' %}"></script>
<script>
$().ready(function() {
  $(".post-list").on("fn.tipuesearch", function() {
    alert(1);
  });
});
</script>

blog/templates/blog/includes/scripts_footer.html
<script>
  $(document).foundation();
</script>

{% if google_analytics %}
<!-- Asynchronous Google Analytics snippet -->
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', '{{ GOOGLE_ANALYTICS_UA }}', 'auto');
  ga('require', 'displayfeatures');
  ga('send', 'pageview');

</script>
{% endif %}

<script type="text/javascript">
$(document).ready(function() {
  $('#tipue_search_input').tipuesearch({
    'show': 8,
    'mode': 'json',
    'contentLocation': '{{ SITEURL }}/tipuesearch_content.json'
  });
});
</script>

<script>NProgress.start();var interval=setInterval(function(){NProgress.inc()},1000);jQuery(window).load(function(){clearInterval(interval);NProgress.done()});jQuery(window).unload(function(){NProgress.start()});</script>

blog/templates/blog/index.html
{% extends 'blog/layouts/page.html' %}
{% load static %}
{% block title %}Pyladies DF - Sobre{% endblock %}

{% block content %}
    <article class="notepad-page-content">
        <div class="title small-12 columns">
            <h1>SOBRE</h1>
        </div>
        <div>
            <figure>
                <img style="height: 230px; padding: -50px;" src="{% static '../../static/blog/img/logo.png' %}" alt="PyLadies">
            </figure>
            <br/>
            <p class="about-text">
            O PyLadies é uma comunidade mundial que foi trazida ao Brasil com o propósito de instigar mais mulheres a entrarem na área tecnológica. Queremos mudar essa realidade de poucas garotas em uma área tão rica e fantásticas como a computação. E olhe que temos muita história nesse campo, viu?!
            </p>
            <p class="about-text">
            Nós percebemos que não haviam motivos para sermos poucas em salas de cursos universitários e técnicos de informática e tecnologia pelo Brasil, então resolvemos nos organizar para dar um jeitinho nisso. Foi então que encontramos outras ladies pelo mundo, que se reuniam em nome da programação e falavam de abstração de um jeito que só ladies sabem falar.
            </p>
            <br/>

            <p class="about-text">
            Nosso desejo é mostrar às meninas que não há limites para sua capacidade intelectual. Se o desejo delas é escrever linhas de código. Pá! Façam isso. Se quiserem desenvolver super sistemas embarcados. Pá! Desenvolvam. Se querem só brincar fazendo algumas linhas de script python. Pá! Brinquem. E se quiserem revolucionar o mundo mesmo sem ter seu código fonte. Pá! Revolucionem. Por que vocês são capazes.
            </p>
            <p class="about-text">
            Nosso propósito não é segregar, pelo contrário, queremos criar o ambiente para que mais meninas sejam atraídas pela tecnologia. Nosso desejo é fazer com que elas nos vejam e pensem "Eu quero estar aí também!".
            </p>
            <p class="about-text"><i>Participar do Dojo foi muito legal! Uma experiência que quero repetir muitas e muitas vezes. Além de aprender de uma forma bem diferente e rápida, também pude fazer amizades e conhecer melhor esse mundo tão grande e divertido do python.</i>
            **Sara Maria**</p>
        </div>
    </article>
    <div class="cf"></div>

{% endblock %}

blog/templates/blog/ladies.html
{% extends 'blog/layouts/page.html' %}

{% load static %}

{% block title %}Pyladies DF - Ladies{% endblock %}
{% block content %}
<article class="notepad-page-content">
  <div class="title small-12 columns">
    <h1>LADIES</h1>
  </div>
  <div>
    <div id="archive">
      <div class="wrap wrap-events">
        <div class="large-12 columns-events">
          <ul class="grid large-block-grid-6 locations-grid">
            {% for lady in ladies %}
              <li class="location">
                <div>

                  <img src="  {% static 'blog/img/ladies/' %}{{ lady.image }}">
                </div>
                {% if lady.url %}
                  <a href="{{ lady.url }}">
                    <span class="lady-name">{{ lady.name }}</span>
                    <i class="fa fa-external-link lady-external-link" aria-hidden="true"></i>
                  </a>
                {% else %}
                  <span class="lady-name">{{ lady.name }}</span>
                {% endif %}
                <p class="lady-city">{{ lady.cidade }}</p>
                <div class="social-icons">
                  {% for item in medias %}
                    {% if item in lady %}
                    <a href="http://{{ item }}.com/{{ lady.item }}">
                      <span class="fa-stack fa-lg">
                        <i class="fa fa-circle fa-stack-2x fa-inverse"></i>
                        <i class="fa fa-{{ item }} fa-stack-1x"></i>
                      </span>
                    </a>
                    {% endif %}
                  {% endfor %}
                </div>
              </li>
            {% endfor %}
          </ul>
        </div>
      </div>
    </div>
  </div>
</article>
{% endblock %}

blog/templates/blog/layouts/base.html
<!DOCTYPE html>
<html>
    <head>
    {% include 'blog/includes/head.html' %}
    {% block extra_meta %}
      <meta name="description"
            content="Ninguém pode fazer você se sentir inferior sem o seu consentimento (Eleanor Roosevelt)">
    {% endblock %}
	{% include 'blog/includes/scripts.html' %}
    </head>
    <body class="{% block body_class %}{% endblock %}">
        <header class="notepad-site-head">
            {% include 'blog/includes/header.html' %}
            {% block extra_header %}{% endblock %}
        </header>
        <main class="notepad-content row" role="main">
          {% block content %}{% endblock %}
        </main>
        {% include 'blog/includes/footer.html' %}
        {% include 'blog/includes/scripts_footer.html' %}
    </body>
</html>

blog/templates/blog/layouts/page.html
{% extends "blog/layouts/base.html" %}
{% block title %}{{ page.title }}{% endblock %}

{% block extra_meta %}
  {% if page.description %}
  <meta name="description" content="{{ page.description }}">
  <meta name="twitter:description" content="{{ page.description }}">
  <meta property="og:description" content="{{ page.description }}">
  {% endif %}

  {% if page.imagefeatured %}
  <meta name="twitter:image" content="{{ SITEURL }}/theme/images/{{ page.imagefeatured }}">
  <meta property="og:image" content="{{ SITEURL }}/theme/images/{{ page.imagefeatured  }}">
  {% endif %}

  <meta name="twitter:title" content="{{ page.title }}">
  <meta name="twitter:creator" content="@PyLadiesDF">
  <meta property="og:locale" content="pt_BR">
  <meta property="og:type" content="article">
  <meta property="og:title" content="{{ page.title }}">
  <meta property="og:url" content="{{ SITEURL }}/{{ page.slug }}">
{% endblock %}



{% block content %}
    <article class="notepad-page-content">
        <div class="title small-12 columns">
            <h1>{{ page.title }}</h1>
        </div>
        <div>{{ page.content }}</div>
    </article>
    <div class="cf"></div>
{% endblock %}

blog/templates/blog/materials.html
{% extends 'blog/layouts/page.html' %}

{% block title %}Pyladies DF - Materiais{% endblock %}

{% block content %}
<article class="notepad-page-content">
  <div class="title small-12 columns">
    <h1>MATERIAIS</h1>
  </div>
  <div>
    <div id="archive">
      <div class="wrap wrap-events">

        <div class="large-12 columns-events">
          <ul class="grid large-block-grid-6 locations-grid">
            {% for material in materials %}
            <li>
              <div>
                  <ul>
                      <li>
                          <b>Título:</b> {{material.title}}
                      </li>
                      <li>
                          <b>Link:</b> <a href="{{ material.link }}">{{ material.link }}</a>
                      </li>
                  </ul>
              </div>
            </li>
            {% endfor %}
          </ul>
        </div>
      </div>
    </div>
  </div>
</article>
{% endblock %}

blog/templates/blog/page.html
{% extends "blog/base.html" %}
{% block title %}{{ page.title }}{% endblock %}

{% block extra_meta %}
  {% if page.description %}
  <meta name="description" content="{{ page.description }}">
  <meta name="twitter:description" content="{{ page.description }}">
  <meta property="og:description" content="{{ page.description }}">
  {% endif %}

  {% if page.imagefeatured %}
  <meta name="twitter:image" content="{{ SITEURL }}/theme/images/{{ page.imagefeatured }}">
  <meta property="og:image" content="{{ SITEURL }}/theme/images/{{ page.imagefeatured  }}">
  {% endif %}

  <meta name="twitter:title" content="{{ page.title }}">
  <meta name="twitter:creator" content="@PyLadiesDF">
  <meta property="og:locale" content="pt_BR">
  <meta property="og:type" content="article">
  <meta property="og:title" content="{{ page.title }}">
  <meta property="og:url" content="{{ SITEURL }}/{{ page.slug }}">
{% endblock %}



{% block content %}
    <article class="notepad-page-content">
        <div class="title small-12 columns">
            <h1>{{ page.title }}</h1>
        </div>
        <div>{{ page.content }}</div>
    </article>
    <div class="cf"></div>
{% endblock %}

blog/templates/blog/share.html
<div class="row text-center">
    <section class="notepad-post-share">
        <h4>Gostou? Compartilhe:</h4>
        <a class="twitter-icon" href="https://twitter.com/intent/tweet?text=&quot;{{ article.title }}&quot;%20https://df.pyladies.com{{ request.get_full_path }}%20via%20&#64;pyladiesdf"
            onclick="window.open(this.href, 'twitter-share', 'width=550,height=235');return false;" title="Share on Twitter">
            <i class="fa fa-twitter"></i>
        </a>
        <a class="facebook-icon" href="https://www.facebook.com/sharer/sharer.php?u=https://df.pyladies.com{{ request.get_full_path }}"
            onclick="window.open(this.href, 'facebook-share','width=580,height=296');return false;" title="Share on Facebook">
            <i class="fa fa-facebook"></i>
        </a>
        <a class="google-icon" href="https://plus.google.com/share?url=https://df.pyladies.com{{ request.get_full_path }}"
           onclick="window.open(this.href, 'google-plus-share', 'width=490,height=530');return false;" title="Share on Google+">
            <i class="fa fa-google-plus"></i>
        </a>
    </section>
</div>

themes/default/templates/article.html
{% extends "base.html" %}
{% block title %}{{ article.title|striptags }}{% endblock %}

{% block extra_meta %}
{% if article.description %}
<meta name="description" content="{{ article.description }}">
<meta name="twitter:description" content="{{ article.description }}">
<meta property="og:description" content="{{ article.description }}">
{% endif %}

{% if article.imagefeatured %}
<meta name="twitter:image" content="{{ SITEURL }}/theme/images/{{ article.imagefeatured }}">
<meta property="og:image" content="{{ SITEURL }}/theme/images/{{ article.imagefeatured  }}">
{% endif %}

<meta name="twitter:title" content="{{ article.title }}">
<meta name="twitter:creator" content="@Pyladiesbrazil">
<meta property="og:locale" content="pt_BR">
<meta property="og:type" content="article">
<meta property="og:title" content="{{ article.title }}">
<meta property="og:url" content="{{ SITEURL }}/{{ article.url }}">
{% endblock %}

{% block body_class %}post-template{% endblock %}

{% block extra_header %}
<div class="notepad-post-title-simple row">
    <div class="small-12 columns">
        <div class="notepad-post-meta-simple">
            <h1>{{ article.title }}</h1>
            <p>by <a target="blank" href="{{article.author_url}}">{{ article.author }}</a> &#8212; {% set tagsize = article.tags.size %}{% if tagsize != 0 %}on {% for tag in article.tags %}<a href="{{ SITEURL }}/tags/index.html#{{ tag }}" data-toggle="tooltip" title="Posts tagged with {{ tag }}" rel="tag">{{ tag }}</a>{% if not loop.last %}&nbsp;&comma;&nbsp;{% endif %}{% endfor %}{% endif %} <strong><time datetime="{{ article.date.isoformat() }}">{{ article.date.strftime("%d/%b/%Y") }}</time></strong></p>
        </div>
    </div>
</div>
{% endblock %}

{% block content %}
<article class="notepad-post-content post tag-simple">
    <div>
        {{ article.content }}
    </div>
    <div class="cf"></div>
    {% include 'share.html' %}
    <div class="cf"></div>
    {% if article.comments %}
    <section class="notepad-disqus row">
        <div class="small-12 columns">
            <h1 class="notepad-comments-header">Comments</h1>
            {% include 'disqus_script.html' %}
        </div>
    </section>
    {% endif %}
</article>
{% endblock %}

themes/default/templates/author.html
{% extends "index.html" %}
{% block title %}{{ SITENAME }} - {{ author }}{% endblock %}

themes/default/templates/categories.html
{% extends "base.html" %}
{% block content %}
<ul class="circle">
{% for category, articles in categories %}
	<li><a href="{{ category.url }}">{{ category }}</a></li>
{% endfor %}
</ul>
{% endblock %}

themes/default/templates/category.html
{% extends "index.html" %}
{% block title %}{{ SITENAME }} - {{ category }}{% endblock %}

themes/default/templates/comments.html
{% if DISQUS_SITENAME %}<p><a href="{{ SITEURL }}/{{ article.url }}#disqus_thread">comments</a></p>{% endif %}

themes/default/templates/disqus_script.html
<div id="disqus_thread"></div>
<script type="text/javascript">
    var disqus_shortname = '{{ DISQUS_SITENAME }}'
    var disqus_identifier = "{{ article.url }}";
    var disqus_url = "{{ SITEURL }}/{{ article.url }}";

    (function() {
        var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
        dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
        (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>

themes/default/templates/sitemap.html
<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">

{% for article in articles %}
  <url>
    <loc>{{ SITEURL }}/{{ article.url }}</loc>
    <priority>0.8</priority>
  </url>

  {% for translation in article.translations %}
  <url>
    <loc>{{ SITEURL }}/{{ translation.url }}</loc>
    <priority>0.8</priority>
  </url>
  {% endfor %}
{% endfor %}

{% for page in pages %}
  <url>
    <loc>{{ SITEURL }}/{{ page.url }}</loc>
    <priority>1.0</priority>
  </url>

  {% for translation in page.translations %}
  <url>
    <loc>{{ SITEURL }}/{{ translation.url }}</loc>
    <priority>1.0</priority>
  </url>
  {% endfor %}
{% endfor %}

</urlset>